Automatically install override toolchain when missing.
A typical scenario is:

* I work on a repository that uses `rust-toolchain` to pin to a specific Nightly version
* I run `git pull`, `rust-toolchain` has been changed to update to a new Rust version
* I run `cargo build`

Result before this PR (typically): rustup fails with an error like:

```
error: override toolchain 'nightly-2017-08-31' is not installed
info: caused by: the toolchain file at '/home/simon/projects/servo/rust-toolchain' specifies an uninstalled toolchain
```

A better result would be to install toolchains as needed.

Closes #1218